name: Deploy

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write  # Allows deleting tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0  # Required to fetch full history and tags

      - name: Get tag message
        id: tagmsg
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MESSAGE=$(git for-each-ref --format='%(contents)' ${GITHUB_REF})
          echo "message=$MESSAGE" >> "$GITHUB_OUTPUT"

      - name: Cancel if tag message is not a version bump
        if: ${{ startsWith(steps.tagmsg.outputs.message, 'Bump version') }}
        run: |
          echo "Tag message starts with 'Bump version'. Skipping workflow."
          exit 1

      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

#    TODO: checkout branch on which the tag was created (not linked to tag, need to search (branch -r ...))

#      - name: Delete tag
#        uses: dev-drprasad/delete-tag-and-release@v1.1
#        with:
#          tag_name: v${{ env.version }} #(required) - The name of the tag to delete. This is expected to be solely the tag name, not the name of a git reference.
#          delete_release: false #(optional) default: true - also delete all releases and their assets that are associated to the tag name
#          github_token: ${{ secrets.GH_TOKEN }} # (required) - a GitHub token with write access to the repo where tags and releases will be searched and deleted

#      - name: Create Branch
#        uses: peterjgrainger/action-create-branch@v2.2.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          branch: 'v${{ env.version }}'

#      - name: Checkout main v${{ env.version }} branch
#        uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          ref: v${{ env.version }}
#          fetch-depth: 0  # Required to fetch full history and tags

      - name: Bump lib-ml package version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_COMMIT: "true"
#          BUMPVERSION_TAG: "true"
#          BUMPVERSION_TAG_NAME: "v${{ env.version }}-release"
        with:
          args: --new-version ${{ env.version }} -v
          github-token: ${{ secrets.GH_TOKEN }}
          branch: main

      - name: Configure Git user
        run: |
          git config user.name "Adrian Josan"
          git config user.email "a.josan@tudelft.nl"

      - name: Delete tag version
        run: |
          git tag --delete v${{ env.version }}
          git push origin --delete v${{ env.version }}
          git tag -l

      - name: Create and push new branch
        run: |
          git checkout -b "v${{ env.version }}"
          git push origin "v${{ env.version }}"

      - name: Re-tag version for the new commit
        run: |
          git tag -f v${{ env.version }} -m 'Bump version: from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}'
#          git push origin -f v${{ env.version }}

      - name: Push updated tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tags: true
          force: true

      - name: Check if same versions before and after
        if: steps.bump.outputs.previous-version == steps.bump.outputs.current-version
        run: |
          echo "Same prev and current version."

      - name: Check if bumped
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
